import { z } from "zod"

// ──────────────────────────────────────────────────────────────────────────
// Schema for the FinLegal-Harness "T2" US credit-card task output
// (logic/eval_US_card/persona/workspace_us/**/final_report.json).
// This is a DIFFERENT shape from the insurance schema in lib/schemas.ts:
// `findings` (not vulnerabilities), float confidence, severity tiers, and a
// populated `legal_grounds` (TILA statutes + real CourtListener precedents).
// ──────────────────────────────────────────────────────────────────────────

export const CARD_TAXONOMY: Record<string, { label: string; description: string }> = {
  "CC-01": { label: "숨겨진/불명확한 수수료", description: "연회비, 해외이용, 현금서비스, 연체 수수료 등이 모호하게 서술" },
  "CC-02": { label: "벌칙 APR / 금리 인상", description: "연체·한도초과 시 향후(또는 기존) 잔액 금리를 인상" },
  "CC-03": { label: "최소결제 함정 / 불리한 청구", description: "평균일일잔액·이중주기 청구 등 이자 부담을 키우는 방식" },
  "CC-04": { label: "일방적 약관변경 / 해지", description: "사전 통지 없이 한도·조건을 변경하거나 계정을 해지" },
  "CC-05": { label: "의무 중재 / 집단소송 포기", description: "소송 대신 중재 강제, 집단소송 권리 포기 조항" },
  UNCATEGORIZED: { label: "기타 소비자 불이익", description: "CC-01~05에 명확히 들어맞지 않는 소비자 불리 조항" },
}

export type CardProductKey = "midfirst-rewards" | "apgfcu-agreement" | "apgfcu-disclosure"

// The 3 products that have precomputed harness runs (client-safe metadata).
export const CARD_PRODUCTS: { key: CardProductKey; label: string; issuer: string }[] = [
  { key: "midfirst-rewards", label: "MidFirst Rewards Credit Card", issuer: "MidFirst Bank" },
  { key: "apgfcu-agreement", label: "APGFCU Visa — Cardholder Agreement", issuer: "APGFCU" },
  { key: "apgfcu-disclosure", label: "APGFCU Visa — Disclosure", issuer: "APGFCU" },
]

// Credit-behaviour personas used by the harness (optional in the UI).
export const CARD_PERSONAS: { id: string; label: string; summary: string }[] = [
  { id: "P01", label: "직장인 (잔액 보유)", summary: "45세 · 회사원 · 중간소득 · 잔액 이월" },
  { id: "P02", label: "긱워커 (불규칙 소득)", summary: "28세 · 긱워커 · 저소득 · 연체 이력" },
  { id: "P03", label: "은퇴자 (고정소득)", summary: "67세 · 은퇴 · 고정소득 · 고령/신용위험" },
]

export const CARD_SEVERITY_COLORS: Record<
  string,
  { bg: string; text: string }
> = {
  CRITICAL: { bg: "bg-red-600", text: "text-white" },
  HIGH: { bg: "bg-orange-500", text: "text-white" },
  MEDIUM: { bg: "bg-yellow-500", text: "text-black" },
  LOW: { bg: "bg-blue-500", text: "text-white" },
}

export const CARD_RISK_LEVEL_COLORS: Record<string, string> = {
  HIGH: "text-red-600",
  MEDIUM: "text-orange-500",
  LOW: "text-yellow-600",
  NONE: "text-green-600",
}

export const CARD_DISCLAIMER =
  "This report is generated by AI analysis and has no legal effect. For specific legal advice, consult a consumer protection attorney or contact the CFPB (1-855-411-2372, consumerfinance.gov)."

// ── Request schema ──────────────────────────────────────────────────────────

export const cardAnalysisRequestSchema = z.object({
  // Optional: a precomputed run is served from product (+ persona) alone.
  contractText: z.string().optional(),
  product: z.string().optional(),
  personaId: z.string().optional(),
  // Optional LLM model id (lib/models.ts). Defaults server-side when omitted.
  model: z.string().optional(),
})

export type CardAnalysisRequest = z.infer<typeof cardAnalysisRequestSchema>

// ── Report schema (mirrors final_report.json) ────────────────────────────────

export const cardStatuteSchema = z.object({
  law_name: z.string(),
  article: z.string(),
  verified: z.boolean().optional(),
})

export const cardPrecedentSchema = z.object({
  case_number: z.string().optional(),
  case_name: z.string(),
  court: z.string().optional(),
  date: z.string().optional(),
  summary: z.string().optional(),
  relevance_score: z.number().optional(),
  source: z.string().optional(),
  url: z.string().optional(),
})

export const cardLegalGroundsSchema = z.object({
  statutes: z.array(cardStatuteSchema).default([]),
  precedents: z.array(cardPrecedentSchema).default([]),
})

export const cardRecommendedActionSchema = z.object({
  action: z.string(),
  priority: z.string(),
  contact: z.string().nullable().optional(),
})

export const cardFindingSchema = z.object({
  finding_id: z.string(),
  taxonomy: z.string(),
  title: z.string(),
  triggered_by: z.string(),
  description: z.string().optional(),
  status: z.enum(["CONFIRMED", "UNVERIFIED", "REJECTED"]).optional(),
  confidence: z.number().min(0).max(1).optional(),
  user_relevance_score: z.number().min(0).max(1).optional(),
  legal_grounds: cardLegalGroundsSchema.optional(),
  severity: z.enum(["CRITICAL", "HIGH", "MEDIUM", "LOW"]).optional(),
  plain_language_explanation: z.string().optional(),
  user_impact: z.string().optional(),
  estimated_risk_scenario: z.string().optional(),
  recommended_actions: z.array(cardRecommendedActionSchema).optional(),
  rank: z.number().optional(),
})

export type CardFinding = z.infer<typeof cardFindingSchema>

export const cardProfileSchema = z
  .object({
    id: z.string().optional(),
    age: z.number().optional(),
    occupation: z.string().optional(),
    financial_status: z.string().optional(),
    risk_flags: z.array(z.string()).optional(),
  })
  .passthrough()

export const cardVulnCountSchema = z.object({
  CRITICAL: z.number(),
  HIGH: z.number(),
  MEDIUM: z.number(),
  LOW: z.number(),
  uncategorized: z.number(),
})

export const cardReportSchema = z.object({
  session_id: z.string().optional(),
  generated_at: z.string().optional(),
  product: z.string(),
  doc_type: z.string().optional(),
  user_profile: cardProfileSchema.optional(),
  executive_summary: z.string().optional(),
  overall_risk_level: z.enum(["HIGH", "MEDIUM", "LOW", "NONE"]).optional(),
  vulnerability_count: cardVulnCountSchema,
  findings: z.array(cardFindingSchema),
  general_recommendations: z.array(z.string()).default([]),
  disclaimer: z.string(),
  source: z.enum(["precomputed", "live"]).optional(),
})

export type CardReport = z.infer<typeof cardReportSchema>
