import { z } from "zod"

// ──────────────────────────────────────────────────────────────────────────
// Schema for the FinLegal-Harness US loan/credit-agreement task output.
// Mirrors lib/card-schemas.ts (same report shape) but with a loan-specific
// taxonomy (LOAN-01..05), no persona, and live-only analysis (no precomputed
// reports). Taxonomy labels come from
// logic/eval_US_loan/results/us_loan_summary.json.
// ──────────────────────────────────────────────────────────────────────────

export const LOAN_TAXONOMY: Record<string, { label: string; description: string }> = {
  "LOAN-01": { label: "가속조항 (기한이익 상실)", description: "경미한 사유로도 대출 전액을 즉시 상환하도록 요구할 수 있는 조항" },
  "LOAN-02": { label: "중대한 부정적 변화 (MAC)", description: "모호한 'Material Adverse Change' 정의로 대주가 일방적으로 의무를 거절·해지" },
  "LOAN-03": { label: "중도상환 위약금", description: "조기 상환 시 과도한 프리미엄·메이크홀·위약금을 부과" },
  "LOAN-04": { label: "교차채무불이행 (Cross-default)", description: "다른 계약의 채무불이행이 본 대출의 채무불이행으로 연쇄 확산" },
  "LOAN-05": { label: "후순위 (Subordination)", description: "차주의 권리·담보가 다른 채권자보다 후순위로 밀리는 조항" },
  UNCATEGORIZED: { label: "기타 차주 불이익", description: "LOAN-01~05에 명확히 들어맞지 않는 차주 불리 조항" },
}

export const LOAN_SEVERITY_COLORS: Record<
  string,
  { bg: string; text: string }
> = {
  CRITICAL: { bg: "bg-red-600", text: "text-white" },
  HIGH: { bg: "bg-orange-500", text: "text-white" },
  MEDIUM: { bg: "bg-yellow-500", text: "text-black" },
  LOW: { bg: "bg-blue-500", text: "text-white" },
}

export const LOAN_RISK_LEVEL_COLORS: Record<string, string> = {
  HIGH: "text-red-600",
  MEDIUM: "text-orange-500",
  LOW: "text-yellow-600",
  NONE: "text-green-600",
}

export const LOAN_DISCLAIMER =
  "This report is generated by AI analysis and has no legal effect. For specific legal advice, consult a qualified finance or securities attorney. Source documents are public SEC EDGAR filings."

// ── Request schema ──────────────────────────────────────────────────────────

export const loanAnalysisRequestSchema = z.object({
  contractText: z.string().optional(),
  product: z.string().optional(),
})

export type LoanAnalysisRequest = z.infer<typeof loanAnalysisRequestSchema>

// ── Report schema (mirrors the card report shape) ─────────────────────────────

export const loanStatuteSchema = z.object({
  law_name: z.string(),
  article: z.string(),
  verified: z.boolean().optional(),
})

export const loanPrecedentSchema = z.object({
  case_number: z.string().optional(),
  case_name: z.string(),
  court: z.string().optional(),
  date: z.string().optional(),
  summary: z.string().optional(),
  relevance_score: z.number().optional(),
  source: z.string().optional(),
  url: z.string().optional(),
})

export const loanLegalGroundsSchema = z.object({
  statutes: z.array(loanStatuteSchema).default([]),
  precedents: z.array(loanPrecedentSchema).default([]),
})

export const loanRecommendedActionSchema = z.object({
  action: z.string(),
  priority: z.string(),
  contact: z.string().nullable().optional(),
})

export const loanFindingSchema = z.object({
  finding_id: z.string(),
  taxonomy: z.string(),
  title: z.string(),
  triggered_by: z.string(),
  description: z.string().optional(),
  status: z.enum(["CONFIRMED", "UNVERIFIED", "REJECTED"]).optional(),
  confidence: z.number().min(0).max(1).optional(),
  user_relevance_score: z.number().min(0).max(1).optional(),
  legal_grounds: loanLegalGroundsSchema.optional(),
  severity: z.enum(["CRITICAL", "HIGH", "MEDIUM", "LOW"]).optional(),
  plain_language_explanation: z.string().optional(),
  user_impact: z.string().optional(),
  estimated_risk_scenario: z.string().optional(),
  recommended_actions: z.array(loanRecommendedActionSchema).optional(),
  rank: z.number().optional(),
})

export type LoanFinding = z.infer<typeof loanFindingSchema>

export const loanVulnCountSchema = z.object({
  CRITICAL: z.number(),
  HIGH: z.number(),
  MEDIUM: z.number(),
  LOW: z.number(),
  uncategorized: z.number(),
})

export const loanReportSchema = z.object({
  session_id: z.string().optional(),
  generated_at: z.string().optional(),
  product: z.string(),
  doc_type: z.string().optional(),
  executive_summary: z.string().optional(),
  overall_risk_level: z.enum(["HIGH", "MEDIUM", "LOW", "NONE"]).optional(),
  vulnerability_count: loanVulnCountSchema,
  findings: z.array(loanFindingSchema),
  general_recommendations: z.array(z.string()).default([]),
  disclaimer: z.string(),
  source: z.enum(["live"]).optional(),
})

export type LoanReport = z.infer<typeof loanReportSchema>
